### ISSUE TITLE
Capabilities set in GetVersion

### ISSUE THREAD

**Issue by eropple** [Palakis/obs-websocket#102]
#### Issue type
Feature request

#### Description
When writing clients against `obs-websocket`, it's pretty difficult to get a good idea of what versions support what features without making a call (and eating an error). This is somewhat amplified by the tendency for most people, at least in my neck of the woods, to be using non-official releases for one feature or another.

Adding an array of capabilitiy strings (or a moral equivalent) to `GetVersion`, or to a new call (`GetServerCapabilities`?) that indicated what a given server actually supports would allow for stuff consuming `obs-websocket-js` or other similar tools to dynamically enable and disable features based on something less ambiguous than a version number and let clients write more rugged code.

**Comment by haganbmj** [comment]
I was tempted to write versioning into `obs-websocket-js` where it would determine the API version and map commands/params to that version similar to what you're requesting, but it wound up being more effort than it was worth on my end and was winding up very messy due to some of the changes in the earlier versions of this. Felt like I better idea to just provide direct passthrough and hope everyone just worked against whatever was latest.

**Comment by eropple** [comment]
I totally agree that it doesn't make sense in the client (and the JS client isn't the only one out there too, I've got an iOS one I need to open source), I was mostly using it as an example. 

Relying on version numbers isn't sufficient given the way that obs-websocket's releases are structured, though. My iOS client white-lists calls based on PROTOCOL.md at time of release. But because features are coming out more rapidly than releases, folks who are using my code are usingartifacts called "4.1.0" that I'm pretty astute (Not 100%) don't actually support Studio Mode calls, though if you download one today it does. With a more rapid cadence that might be an easier thing to swallow, but I've found myself running into folks who are pretty fragmented with regard to versions like this and a set of cap flags would go a long way towards addressing this fragmentation, if not solving it.

**Comment by haganbmj** [comment]
Sure, ideally this would just have a minor/patch release every change.
So would you think just a list of API methods would be sufficient to get started?
```json
"obs-websocket-version": "4.1.0",
"availableRequests": [ "GetSceneList", "GetVersion", ... ]
```

**Comment by eropple** [comment]
Requests and events--I think that'd be solid? Plus then both your obs-websocket-js and my iOS library can just dynamically provision API endpoints after `GetVersion`, yeah?

**Comment by haganbmj** [comment]
Yeah, I wouldn't mind being able to throw a `NotDefined` error or something.
https://github.com/haganbmj/obs-websocket-js/blob/master/lib/API.js

**Comment by haganbmj** [comment]
Looks like just returning the contents of messageMap would be sufficient for requests.
https://github.com/Palakis/obs-websocket/blob/master/WSRequestHandler.cpp#L43

In the mean time though just catching `invalid request type` is sufficient for most cases.

**Comment by Palakis** [comment]
That's an interesting discussion, here. It's quite easy to provide a list of supported request types in the response of `GetVersion` thanks to `WSRequestHandler::messageMap`.
Adding a list of supported events will require the addition of a data structure (list of events) just for this purpose. To avoid possible inconsistencies between the actual events available and the events listed, a check could be done when sending an event.

----

> Relying on version numbers isn't sufficient given the way that obs-websocket's releases are structured, though.

obs-websocket uses Semantic Versioning (major.minor.bugfix). To sum up the idea of SV: "bugfix" increases when no API change is made, "minor" increases when backwards-compatible changes happen (e.g.: new commands), "major" increases when compatibility-breaking changes happen in the API.
This isn't a magic bullet, but might be sufficient for a library to detect if it can work with a said server version or tell the user an upgrade is recommended or needed (in the worst case scenario)

----

> This is somewhat amplified by the tendency for most people, at least in my neck of the woods, to be using non-official releases for one feature or another.

People doing so do it at their own risk. These are development builds meant to test the latest features and bugfixes, not official releases ready for production nor some sort of "rolling releases". I tend to think this happens because 4.1 has and will have a lot of much-requested additions, especially Studio Mode control.

Btw, what/who do you define by "most people, at least in my neck of the woods"? I'm always curious to know what people achieve with obs-websocket! 😄

**Comment by lebaston100** [comment]
> I'm always curious to know what people achieve with obs-websocket! 
I made a [multiview tally system](https://github.com/lebaston100/OBSmultiviewTally) which requires the new studio features so i have to use a newer build.
Some sort of version request would be appreciated. From my perspective the version numbering would be sufficient.

**Comment by eropple** [comment]
@Palakis I'm building mobile tooling for OBS right now, which is probably why a lot of people are very anxious about release versioning. Like, if I were going to release this publicly right now, I'd tell people to use a development version of 4.1 because of the Studio Mode changes.

**Comment by haganbmj** [comment]
Could certainly use a release now just to lock in the new request types.
It's been over 200 commits.
https://github.com/Palakis/obs-websocket/compare/4.0.0...master

**Comment by Palakis** [comment]
@haganbmj Good idea.

**Comment by Palakis** [comment]
Done. Just tagged 4.1.0 as pre-release.

By the way, I slimmed down the priorities for 4.2.0 in order to have only easy or important things to implement. Corresponding project here: https://github.com/Palakis/obs-websocket/projects/5

**Comment by haganbmj** [comment]
Hoorah

**Comment by Palakis** [comment]
Is the API version number in `GetVersion` actually useful?

**Comment by haganbmj** [comment]
As a consumer I have no idea what version of the plugin is in use.
I'm not opposed to just encouraging defensive programming and handling errors when a request isn't supported.

**Comment by Palakis** [comment]
> As a consumer I have no idea what version of the plugin is in use.

That's not what I meant with my comment above. I was wondering if the `api-version` field provided in GetVersion's response is actually useful, given that the version number of the plugin already serves as a mean to detect API changes or state.

> I'm not opposed to just encouraging defensive programming and handling errors when a request isn't supported.

Me too.

**Comment by haganbmj** [comment]
That said [this issue](https://github.com/haganbmj/obs-websocket-js/issues/62) took like 2 minutes to resolve because I knew what the plugin version they were using was. I'm debating storing the version details and attaching them to all messages so that people can figure that stuff out.

**Comment by Palakis** [comment]
My bad, I was talking about the `version` field of GetVersion. `api-version` doesn't exist.

**Comment by Palakis** [comment]
In obs-websocket.h:
```cpp
#define OBS_WEBSOCKET_VERSION "4.2.0"
#define API_VERSION 1.4
```

In WSRequestHandler.cpp, under `HandleGetVersion`:
```cpp
obs_data_t* data = obs_data_create();
obs_data_set_double(data, "version", API_VERSION);
obs_data_set_string(data, "obs-websocket-version", OBS_WEBSOCKET_VERSION);
```

There's no clear guideline on how `API_VERSION` should be maintained/updated, so I'm thinking about removing this attribute. However, no need to talk about how the plugin version is useful. 😄

**Comment by haganbmj** [comment]
I didn't even know that api-version was there.
