### ISSUE TITLE
Feature Request: onReplaySave event

### ISSUE THREAD

**Issue by makeen** [Palakis/obs-websocket#119]
Issue type
Feature request

Description
I need send "SaveReplayBuffer" request to a 12 remotes OBS when I save replay buffer In a thirteenth OBS with hotkey, because of that an event "onReplaySave" save my life.

**Comment by Palakis** [comment]
Good idea. Do you think you could explore OBS' source code to see if this is implementable?

**Comment by makeen** [comment]
Is posible catch hotkeys from your plugin?

**Comment by cthurston** [comment]
For my case, I would love that the SaveReplayBuffer wait until the file is written then return the file path.

**Comment by XBase-xOR** [comment]
> For my case, I would love that the SaveReplayBuffer wait until the file is written then return the file path.

Same here, currently I am using a file watcher to find out when a replay file is written and then process it from my program, but the problem is the watcher is not very precise, it's already triggered at some random point while the file is being written. Right now I just wait 1 second after the last activity on the file to be on the safe side, but such code is not very clean and prone to break when timings change, which could happen due to various reasons (e.g. current disk load on the computer).

With this event waiting for the file to be written and returning the file path a file watcher would no longer be necessary and the file could immediately be processed as soon as it was written.

This is a bit similar to #640 - or what would also help is if #311 would be implemented (at least in my case, since I am triggering the replay buffer save myself this way).

**Comment by YorVeX** [comment]
> For my case, I would love that the SaveReplayBuffer wait until the file is written then return the file path.

Same here, currently I am using a file watcher to find out when a replay file is written and then process it from my program, but the problem is the watcher is not very precise, it's already triggered at some random point while the file is being written but not finished yet. Right now I just wait 1 second after the last activity on the file to be on the safe side, but such code is not very clean and prone to break when timings change, which could happen due to various reasons (e.g. current disk load on the computer).

With this event waiting for the file to be written and returning the file path a file watcher would no longer be necessary and the file could immediately be processed as soon as it was written.

This is a bit similar to #640 - or what would also help is if #311 would be implemented (at least in my case, since I am triggering the replay buffer save myself this way).

**Comment by tt2468** [comment]
Planned for 5.0.0
