### ISSUE TITLE
obs.onSceneItemVisibilityChanged not triggered ?

### ISSUE THREAD

**Issue by illusdidi** [Palakis/obs-websocket#177]
##### Issue type
Bug report ?

##### Steps to reproduce and other useful info
I don't know if it's normal or not, but the event SceneItemVisibilityChanged is only triggered when the item is in the current visible scene. It is not triggered if the item is not on another scene (even if the item is in the scene that is currently in preview on studio mode).

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : OBS Studio 64 bit 20.1.2
Using obs-websocket-js v0.8.0

**Comment by Palakis** [comment]
Ah right, it's because the current implementation is a bit hacky:
https://github.com/Palakis/obs-websocket/blob/master/src/WSEvents.cpp#L246-L247

Currently there's no way to track all sources and scene items and bind signals to events on them, and that would be the ideal solution. That's definitely something I'll introduce in 5.0.0.

**Comment by illusdidi** [comment]
Okay thanks a lot !

**Comment by Exavior** [comment]
Please please please tell me this has been addressed.  The entire application I'm developing around this depends on observing the visible state of items in a scene that is not currently visible.
