### ISSUE TITLE
Need to change encoding bitrate

### ISSUE THREAD

**Issue by ethaniel** [Palakis/obs-websocket#213]
I'm using OBS for a remote webcam. It would be cool to be able to control the encoding bitrate via the API:

![image](https://user-images.githubusercontent.com/941973/39484078-c7af9ebe-4d9e-11e8-964e-2c4b19040c69.png)

During daytime, I broadcast at 6000 kilobits per second. During nighttime (when the image is dark and almost nothing is visible) I would lower down to 1500 kilobits to save on bandwidth.

Also, when there are lost network packets, I could detect that via the websocket and lower the bitrate accordingly.

**Comment by f5uii** [comment]
Yes, this function would be very useful for us among radio amateurs who broadcast DVBS2 programmes via satellite. We control the spectrum width and the useful bit rate via CBR. I do not take to these developments of interface with [PlutoDVB ](https://github.com/F5OEO/datvplutofrm)(modulation and SDR transmitter).

**Comment by tt2468** [comment]
This is basically not possible right now due to how the encoder system in OBS is built. Every type of encoder has a different way of storing the stream bitrate, and for example the ffmpeg (advanced mode) encoder stores data in a .json file which we cannot predict the location of. Unfortunately, this means that setting the stream bitrate may never be possible.

**Comment by matiaspl** [comment]
Well, if there's a way to access hotkeys remotely or start recording, why would there be no way to fill in the value as you would do in the GUI? It's done the same way for recording support in obs-websocket. All encoders share common naming scheme (the name "bitrate" is shared among QSV,AMF, NVENC and x264), we can get currently selected encoder, we can access it's properties. Not storing the value is another story, but just setting it should be doable the same way as it is done in https://github.com/obsproject/obs-studio/blob/master/UI/window-basic-main-outputs.cpp 
... or am I missing something? :)

**Comment by tt2468** [comment]
Because under the hood, calling `obs_frontend_start_streaming()` uses `QMetaObject::invokeMethod()` which is basically just a way of triggering the same function as pressing the "start streaming" button does, however the settings menu is a whole beast, where opening the menu calls a bunch of functions to fill in information, and closing the menu does almost an equal amount of work. We also are missing access to most of that data anyway, as the obs frontend api only exposes certain endpoints.

**Comment by matiaspl** [comment]
I was under the impression that https://github.com/obsproject/obs-studio/blob/master/UI/window-basic-main-outputs.cpp#L1329 kind of does it in two simple calls, but the last time I wrote something in C++ was around 20 years ago :)

**Comment by tt2468** [comment]
While we could access the service and encoder, we would not have access to the `settings` object created here: https://github.com/obsproject/obs-studio/blob/master/UI/window-basic-main-outputs.cpp#L1326

Technically if we replicated enough frontend functionality ourselves, setting the encoder bitrate would be possible. However, it quickly becomes too big to manage.

**Comment by leporel** [comment]
this works
```
      await this.obsSocket.call('SetProfileParameter', {
        parameterCategory: "SimpleOutput",
        parameterName: "VBitrate",
        parameterValue: "2500"
      });
``
but unfortunately, although the values are changed, it does not repeat the behavior if we pressed “apply” while the stream is active, which changes the bitrate of the stream. SetProfileParameter dont “apply” changes like a settings window.
