### ISSUE TITLE
Groups-functionality breaks everything

### ISSUE THREAD

**Issue by Symbiatch** [Palakis/obs-websocket#237]
##### Issue type
Bug report

##### Description
When using grouping in OBS Studio the sources can't be used at all

##### Steps to reproduce and other useful info
Add a group, put a source in it. There will be no events for visibility of that source and they cannot be addressed via the API, for example hide/show doesn't do anything. The group itself does send events and can be hidden/shown.

##### Technical information
OBS Studio 22
Windows 10

**Comment by pantonvich** [comment]
Source inside a Source has the same issue.

**Comment by Palakis** [comment]
@pantonvich What do you mean by "source inside a source"?

**Comment by pantonvich** [comment]
sorry that should be source inside a scene inside a scene - you don't have access to that source. so if you have two scenes A & B. scene A has source A (like a browser or text(gdi+)). scene B has scene A (and source A). When scene B is active you can't hide/un-hide source A. If scene A is active then you can hide/un-hide source A. Back when I looked at this the issue is that obs doesn't provide access to sources inside scenes and groups that are inside a different scene. Back in September I was going to try and fix this but it was over my head with how sources inside obs are handled - and I think that it requires code in obs to allow websockets to access those sources inside of scene inside of scene/group collections. I don't know if anything has changed inside of obs since September to allow access.

**Comment by Palakis** [comment]
Did some testing with the latest dev version: the scene item events refactor fixed the issue of scene item events not triggered when an item belongs to a group.

Now I need to check which request types don't go along well with groups.

**Comment by Palakis** [comment]
Ran some tests and all scene item events trigger properly for scene items nested in a group. However, scene item requests are indeed broken when targeting a scene item contained within a group.

To do list:

- [ ] Add events to signal when a scene item is added to/removed from a group
- [ ] Source info (in event data and request responses): add a `children` property containing a list of sub-items
- [ ] Fix scene item requests: GetSceneItemProperties, SetSceneItemProperties, ResetSceneItem, DeleteSceneItem, DuplicateSceneItem
    - Bonus: fix deprecated request types: SetSceneItemRender, SetSceneItemPosition, SetSceneItemTransform, SetSceneItemCrop
- [ ] Bonus: add  `GetParent`/`SetParent` method to get/set the parent of a source/scene item ?
