### ISSUE TITLE
Add recording filename to StartRecording/StopRecording response

### ISSUE THREAD

**Issue by djardine** [Palakis/obs-websocket#258]
##### Issue type
Feature request

##### Description
Would to be possible to add the filename (and path?) or the recorded file to the response of StartRecording and/or StopRecording? Better yet, how about passing in a filename to save the recording to when calling StartRecording? Thanks!

**Comment by Palakis** [comment]
> Would to be possible to add the filename (and path?) or the recorded file to the response of StartRecording and/or StopRecording?

Sure!

> Better yet, how about passing in a filename to save the recording to when calling StartRecording? Thanks!

Could be possible, I just need to check if this breaks anything with OBS' recording UX.

**Comment by Palakis** [comment]
What I believe should be implemented:

- Provide the current recording filename in:
    - The response from StartRecording and StopRecording
    - Recording events
    - StreamStatus and Heartbeat events
- Ability to force a specific recording file path when calling StartRecording

**Comment by tomierna** [comment]
I'm doing motion detection on an OBS stream, and triggering StartRecording when I see movement over a certain threshold, and then sending out alerts linking to these files. I'm running into a race condition where certain URLs will be incorrect because the second counter changes between the time OBS generates the name and when I generate the URL.

Having the OBS-chosen filename passed back as the response to StartRecording would be a great solution to this problem.

**Comment by Palakis** [comment]
I found a way to fetch the destination filename during a recording, however I can't make it available in the response of StartRecording, as this information is not yet available when this function returns. See #621 for more details.

**Comment by leafac** [comment]
Is there a way to get the recording file name in the version of `obs-websocket` that has been released (4.8)? `GetRecordingStatus` isn’t available yet, and `GetStreamingStatus` doesn’t include that information.
