### ISSUE TITLE
Best Practice on Heavy Usage?

### ISSUE THREAD

**Issue by Huesdon** [Palakis/obs-websocket#310]
**##### Issue type**
Question (Usage)

**##### Description**
I am using the sockets to animate a fade of a source. Works good., however,
after some time obs becomes unresponsive and crashes when you click on anything within the obs window.

**##### Steps to reproduce and other useful info**
I suspect I am overwhelming the plugin/obs as I am making many calls per second to get a smooth fade. 

**##### QUESTIONS:**
-can the plugin handle many calls per second?
-if so, how best to do so...

**Should I:**
-open a websocket
-connect, do stuff, disconnect -on every call  

**OR**

-open a websocket
-connect and reuse it over and over

**##### Technical information**
- Windows 10
- OBS v.23.1.0

**Comment by Palakis** [comment]
@Huesdon obs-websocket before 4.6 use Qt's WebSocket server, which processes requests on the UI thread. 4.6 should fix this, because the new server implementation (using websocketpp) has its own thread for requests processing.

**Comment by Huesdon** [comment]
Ah ok, in fairness, I think I was hitting way too hard. Started with 100 calls to the socket per second. I've dialed it down to 10 per second and the fade isn't too bad.

**Comment by Huesdon** [comment]
W/respect to my question, what you would say is the best practice when using the socket in this manner?
Currently I am connecting and disconnecting on each call, so 10 times per second.

**Comment by macharborguy** [comment]
> W/respect to my question, what you would say is the best practice when using the socket in this manner?
> Currently I am connecting and disconnecting on each call, so 10 times per second.

I would suggest making a single connection to the socket server, then doing all the calls within that connection.  I would also suggest only making the SEND call once per frame that you are broadcasting at at the very most.  If you are doing 60fps, at most only send 60 calls per second, so just around 16-17ms between calls.  For 30fps it would be 33ms between each call.  You could get away with doing half as many calls as well.

If you have more than 1 element that needs to be altered, it may be best to set up an animation queue of sorts, that triggers multiple SENDS (for fading 2 different scene items at relatively the same time).  If you are working with JavaScript, this could simply be a setInterval that runs a check function every ##ms based on the framerate.  That "check function" would then trigger the processing of each elements fade-in-fade-out status for that frame, and if there is a change from the previous frame, trigger the SEND.  If not, simply do nothing.   I attempted to use requestAnimationFrame, however there are issues with RAF and OBS Browser Source where sometimes it doesnt want to actually run properly, whereas SetInterval and SetTimeout run flawlessly.

**Comment by Huesdon** [comment]
Here is the call atm....

> // 2.5 second fade out
  function podiumFadeDown() {
    setPodiumOpacity(96); // first one is free....
    // set values for first run in the loop
    var degree = 92;
    var interval = 100;
    var i = 0;    
    while (i < 24) { // 25 less the one we did above
      // schedule future opacity fade calls and populate podium timers reference array   
      stream.podiumfadeTimers.push(setTimeout(setPodiumOpacity, interval, degree));
      degree = degree - 4;
      interval = interval + 68;
      i++;
    

So right now I have 68ms between calls working backwards from a target of 10 calls per second.
I am going to play with using one connect to see if that helps but after a while doing it this way obs is still crashing out when I click on any control in the obs gui.

@Palakis when should we loosely expect 4.6 to drop?

**Comment by Huesdon** [comment]
Oh and @macharborguy, w/ respect to multiple sources being animated this way. I created a camera "podium" scene and used that as a source w/ opacity filter on it there. That allowed me to have one call and affect several sources at once.

**Comment by macharborguy** [comment]
@Huesdon yes, ive used that method within the past few weeks on one of our team broadcasts in order to fake a camera-zoom-out of a composited scene with multiple layers to it.

Actual usage, im in the R&D video area at the top center -> https://www.twitch.tv/overboredgaming/clip/CheerfulUglyKleeFailFish?filter=clips&range=30d&sort=time

Also notice when I look off camera before the zoom and music plays.  I was pressing a button on a WebApp on my tablet that triggered the animation.

I have a Start and Stop position and scale, calculate the increments based on framerate, and a duration for the zoom to run, then every frame for 60fps I adjust the values of a 3D Transform (was having issues getting source position/scale working, so I went with adjusting a filter instead).  The music starts playing at the very start, and the text overlay is part of the Browser Source that handles the OBS-WebSocket communication, and is faded in and out via a CSS Transition on a timer in Javascript.

What I was suggesting, more or less, is when you have more than one source that needs their own independent effects applied to them per frame.  Like two WebCam or Video Call captures that need to be moved, resized, faded, ...etc, completely differently and independent of eachother, rather than a composited scene that just has a single effect applied to itself.

What I may do in the near future is have everything scripted via DOM elements in a Browser Source, and just relay their position data back to OBS-WebSocket, that way I dont have to do the calculations myself via code, I can just read what the current position, scale and rotation of the DOM elements are and send that instead.

**Comment by Huesdon** [comment]
just ran with the above code for a couple hours and the plugin didnt choke. I run the animation a lot because its triggered when I detect voice on the mic.

**Comment by Palakis** [comment]
@Huesdon btw give a try to obs-websocket 4.6.1. It has a completely new WebSockets server which processes requests in a separate thread.
