### ISSUE TITLE
Commands to change the current profile and scene collection

### ISSUE THREAD

**Issue by ystar8** [Palakis/obs-websocket#34]
hello ！
I suggest adding the profile to the websocket because sometimes it is necessary to change the.

**Comment by Palakis** [comment]
I can work on this as soon as https://github.com/Palakis/obs-websocket/issues/23 is fixed, because the settings of obs-websocket are saved in the current profile.

**Comment by ystar8** [comment]
Thank you.

**Comment by ystar8** [comment]
very nice ..

**Comment by Palakis** [comment]
Protocol changes :

---

#### "SetCurrentSceneCollection"
Change the current scene collection.

__Request fields__ :
- **"sc-name"** (string) : name of the desired scene collection

__Response__ : OK if scene collection exists, error otherwise.

---

#### "GetCurrentSceneCollection"
Get the name of the current scene collection.

__Request fields__ : none

__Response__ : OK with these additional fields :
- **"sc-name"** (string) : name of the current scene collection

---

#### "ListSceneCollections"
Get a list of available scene collections.

__Request fields__ : none

__Response__ : OK with these additional fields :
- **"scene-collections"** (array of objects) : names of available scene collections

---

#### "SetCurrentProfile"
Change the current profile.

__Request fields__ :
- **"profile-name"** (string) : name of the desired profile

__Response__ : OK if profile exists, error otherwise.

---

#### "GetCurrentProfile"
Get the name of the current profile.

__Request fields__ : none

__Response__ : OK with these additional fields :
- **"profile-name"** (string) : name of the current profile

---

#### "ListProfiles"
Get a list of available profiles.

__Request fields__ : none

__Response__ : OK with the additional fields :
- **"profiles"** (array of objects) : names of available profiles

---
