### ISSUE TITLE
Enable/disable filters?

### ISSUE THREAD

**Issue by Symbiatch** [Palakis/obs-websocket#340]
##### Issue type
Feature request

##### Description
I can't see any way currently to enable or disable filters. One can get filters of a source and change their settings, but not enable or disable them. Is this correct? I could probably hack it in myself and send a PR if this feature is missing. I did check the messages GetSourceFilters etc return and there's no field for this.

**Comment by YorVeX** [comment]
Did the same as you, checked the GetSourceFilters response and since there is no field that shows whether it's enabled or disabled I figured you can't set visibility through SetSourceFilterSettings. I also checked the source but there doesn't seem to be any undocumented old method for this either (as exists e.g. for sources with the SetSourceRender method).

I'd really love to have this too. One could probably just remove and add them as needed using AddFilterToSource and RemoveFilterFromSource but boy would that be ugly.
