### ISSUE TITLE
Is there a way to pull source info?

### ISSUE THREAD

**Issue by b3ck** [Palakis/obs-websocket#350]
##### Issue type
Feature request/Other

##### Description
I was wondering if there is a way to pull information from a video source, for example, bitrate, fps, resolution etc..  or is this something I would have to ask the developers of the video source plugin (NDI, VLC etc..) ??

##### Steps to reproduce and other useful info
N/A

##### Technical information
- Windows 10 Pro 64bit :
- OBS Studio 23.2.1 64bit :

##### Development Environment
NODE, NPM

**Comment by Palakis** [comment]
@b3ck Depends what kind of values you're looking for.

Resolution, yes. FPS, potentially. But bitrate, that's another matter. There's currently no standard way of getting bitrate info, because it's specific to a handful of source types. Source-specific info could be provided by sources through callbacks and/or signals.
