### ISSUE TITLE
New request type: SetVideoSettings

### ISSUE THREAD

**Issue by Palakis** [Palakis/obs-websocket#362]
##### Issue type

Feature request

##### Description

Add a new method to change:
   - Base video (canvas) size
   - Rescaled output size
   - Framerate.

**Comment by tt2468** [comment]
Any possibility that an event like OnVideoSettingsChanged could be implemented?

**Comment by Palakis** [comment]
@tt2468 Not that I know of, currently. Haven't really looked into that.

**Comment by tt2468** [comment]
Now pending obsproject/obs-studio#4175

**Comment by tt2468** [comment]
On the sheet for 5.0.0

**Comment by nickfujita** [comment]
Hello @tt2468 just wanted to follow up on this feature.

It seems that [your PR](https://github.com/obsproject/obs-studio/pull/4175) the feature in OBS has since been merged and released in v27.0.

Looks like there was a [PR open to support](https://github.com/Palakis/obs-websocket/pull/430) this by @Palakis, but it was closed instead of merged.

Would it be possible to re-open this PR and get it into the next release?
