### ISSUE TITLE
ETA for 4.8.0?

### ISSUE THREAD

**Issue by ethaniel** [Palakis/obs-websocket#446]
Hi! I've got 2 questions:

1. Is there an ETA fo 4.8.0?
2. What's the best way to financially sponsor this project?

**Comment by tt2468** [comment]
I'm also wondering about question 2

**Comment by Palakis** [comment]
@ethaniel Regarding 1), 4.8.0 will probably be released around mid-April.

@ethaniel @tt2468 Regarding 2), an Open Collective is in the works so that both individuals and companies will be able to donate money towards the project. In the meantime, my personal PayPal donation box is open: https://www.paypal.me/stephanelepin
