### ISSUE TITLE
Adding support for standalone obs studio

### ISSUE THREAD

**Issue by tvvignesh** [Palakis/obs-websocket#536]
Hi. While this works well with obs standard linux installation, it does not work with obs standalone install since it looks for a package named obs-studio which it doesn't find since it is a standalone installation.

Maybe support can be provided by asking us to provide the path to the installation. Just saying.

But, its awesome. Tried with a regular install and its great to see everything working perfectly.

**Comment by HugLifeTiZ** [comment]
This is because the maintainer only packages the plugin as a debian package. So if you didn't install OBS Studio in your package manager, the debian package won't install. You may have some luck extracting the files from the debian package manually, as described in [this issue.](https://github.com/Palakis/obs-websocket/issues/442)

**Comment by tt2468** [comment]
If you are using a standalone installation, then you should simply build from source. Our deb is for standard installations.
