### ISSUE TITLE
[Feature Request] SetSettings to include bitrate

### ISSUE THREAD

**Issue by mrsydster** [Palakis/obs-websocket#676]
##### Issue type

 - Feature request

##### Description

Feature to set the bitrate of the stream

**Comment by tt2468** [comment]
This is basically not possible right now due to how the encoder system in OBS is built. Every type of encoder has a different way of storing the stream bitrate, and for example the ffmpeg (advanced mode) encoder stores data in a .json file which we cannot predict the location of. Unfortunately, this means that setting the stream bitrate may never be possible.
